### ISSUE TITLE
Default to https streams?

### ISSUE THREAD

**Issue by filippog** [MS3FGX/SomaFM#6]
Hi,
thank you for `somafm`! I noticed it defaults to use http streams as opposed to https, I tested the same urls with https and they work fine for me. I believe it'd be fine to switch to https overall, what do you think ?

**Comment by MS3FGX** [comment]
The problem is that HTTPS only works on certain combinations of player/OS. This has caused problems for users in the past, for example when using MPlayer on Mac OS #1 

To make sure the script works on as many systems as possible, it's simply easier to just use the HTTP streams as there's really no practical advantage to using the encrypted versions anyway. Of course, if Soma FM eventually stops offering the streams over plain HTTP then we'll have to revisit this issue.

**Comment by filippog** [comment]
Fascinating, thank you for the explanation and the quick reply -- all makes sense to me!
